## STAGING environment configuration
base.url=https://eventhub.rahulshettyacademy.com
admin.events.path=/admin/events
login.path=/login
events.path=/events
bookings.path=/bookings

test.user.email=muralibv3@gmail.com
test.user.password=Leealilee$231$
